language: python
python:
  - 2.7
addons:
  postgresql: '9.4'
services:
  - redis-server
branches:
  only:
    - master
before_script:
  - psql -c 'create database testproject;' -U postgres
  - pip install pip --upgrade
  - pip install .[test]
  - ./testproject19/manage.py migrate --noinput
script:
  - ./testproject19/manage.py test
