language: python
python:
  - 2.7
addons:
  postgresql: '9.4'
services:
  - redis-server
branches:
  only:
    - master
before_script:
  - psql -f testproject19/travis_setup.sql -U postgres
  - pip install pip --upgrade
  - pip install -e .[test]
  - ./testproject19/manage.py migrate --noinput
script:
  - ./testproject19/manage.py test
